project_id = "pchaijknfmrddivqjesm"

[functions.push-update]
verify_jwt = false

[functions.bot-actions]
verify_jwt = false

[functions.bot-tick]
verify_jwt = false

[functions.kraken-withdraw]
verify_jwt = false

[functions.execute-intents]
verify_jwt = false

[functions.plaid]
verify_jwt = false
